trigger:
  - main

pr:
- '*'

variables:
- name: BUILD_COUNTER
  value: $[counter('buildnumber', 0)]

pool:
  vmImage: windows-latest
steps:
- task: UseDotNet@2
  displayName: Install .NET 6 SDK
  inputs:
    version: '6.0.x'
    packageType: sdk
- task: UseDotNet@2
  displayName: Install .NET Core 3.1 SDK
  inputs:
    version: '3.1.x'
    packageType: sdk
- powershell: ./build.ps1 -ci
  displayName: Invoke build.ps1
- publish: artifacts/
  artifact: Packages
  displayName: Publish artifacts
